FROM jenkins/jenkins:lts

USER root

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-venv python3-pip \
    jq bc docker.io \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Allow Jenkins user to use docker
RUN usermod -aG docker jenkins

USER jenkins

